name: My build action requiring more space
on: workflow_dispatch

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 512
          remove-dotnet: 'true'
          temp-reserve-mb: 64
          remove-android: 'true'
          remove-haskell: 'true'
          
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Free space:"
          df -h 
          df -h /home/
